// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITestAutomationPageObjects.PageObjects.Home.HomePageClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class HomePage
    {
        
        #region Properties
        public UIASPNETMVCMusicStoreWWindow UIASPNETMVCMusicStoreWWindow
        {
            get
            {
                if ((this.mUIASPNETMVCMusicStoreWWindow == null))
                {
                    this.mUIASPNETMVCMusicStoreWWindow = new UIASPNETMVCMusicStoreWWindow();
                }
                return this.mUIASPNETMVCMusicStoreWWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIASPNETMVCMusicStoreWWindow mUIASPNETMVCMusicStoreWWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIASPNETMVCMusicStoreWWindow : BrowserWindow
    {
        
        public UIASPNETMVCMusicStoreWWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "ASP.NET MVC Music Store";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("ASP.NET MVC Music Store");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIASPNETMVCMusicStoreDocument UIASPNETMVCMusicStoreDocument
        {
            get
            {
                if ((this.mUIASPNETMVCMusicStoreDocument == null))
                {
                    this.mUIASPNETMVCMusicStoreDocument = new UIASPNETMVCMusicStoreDocument(this);
                }
                return this.mUIASPNETMVCMusicStoreDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIASPNETMVCMusicStoreDocument mUIASPNETMVCMusicStoreDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIASPNETMVCMusicStoreDocument : HtmlDocument
    {
        
        public UIASPNETMVCMusicStoreDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "ASP.NET MVC Music Store";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:26641/";
            this.WindowTitles.Add("ASP.NET MVC Music Store");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIAlbumlistCustom
        {
            get
            {
                if ((this.mUIAlbumlistCustom == null))
                {
                    this.mUIAlbumlistCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIAlbumlistCustom.SearchProperties["TagName"] = "UL";
                    this.mUIAlbumlistCustom.SearchProperties["Id"] = "album-list";
                    this.mUIAlbumlistCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIAlbumlistCustom.FilterProperties["Class"] = null;
                    this.mUIAlbumlistCustom.FilterProperties["ControlDefinition"] = "id=\"album-list\"";
                    this.mUIAlbumlistCustom.FilterProperties["TagInstance"] = "3";
                    this.mUIAlbumlistCustom.WindowTitles.Add("ASP.NET MVC Music Store");
                    #endregion
                }
                return this.mUIAlbumlistCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIAlbumlistCustom;
        #endregion
    }
}
