// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITestAutomationPageObjects.PageObjects.Store.StoreDetailClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class StoreDetail
    {
        
        #region Properties
        public UIAlbumDetailWindow UIAlbumDetailWindow
        {
            get
            {
                if ((this.mUIAlbumDetailWindow == null))
                {
                    this.mUIAlbumDetailWindow = new UIAlbumDetailWindow();
                }
                return this.mUIAlbumDetailWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAlbumDetailWindow mUIAlbumDetailWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAlbumDetailWindow : BrowserWindow
    {
        
        public UIAlbumDetailWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Album -", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Album - For Those About To Rock We Salute You");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAlbumDetailsDocument UIAlbumDetailsDocument
        {
            get
            {
                if ((this.mUIAlbumDetailsDocument == null))
                {
                    this.mUIAlbumDetailsDocument = new UIAlbumDetailsDocument(this);
                }
                return this.mUIAlbumDetailsDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAlbumDetailsDocument mUIAlbumDetailsDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAlbumDetailsDocument : HtmlDocument
    {
        
        public UIAlbumDetailsDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Album - For Those About To Rock We Salute You";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/2";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:26641/Store/Details/2";
            this.WindowTitles.Add("Album - For Those About To Rock We Salute You");
            #endregion
        }
        
        #region Properties
        public UIAlbumdetailsPane UIAlbumdetailsPane
        {
            get
            {
                if ((this.mUIAlbumdetailsPane == null))
                {
                    this.mUIAlbumdetailsPane = new UIAlbumdetailsPane(this);
                }
                return this.mUIAlbumdetailsPane;
            }
        }
        
        public UIMainPane UIMainPane
        {
            get
            {
                if ((this.mUIMainPane == null))
                {
                    this.mUIMainPane = new UIMainPane(this);
                }
                return this.mUIMainPane;
            }
        }
        #endregion
        
        #region Fields
        private UIAlbumdetailsPane mUIAlbumdetailsPane;
        
        private UIMainPane mUIMainPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAlbumdetailsPane : HtmlDiv
    {
        
        public UIAlbumdetailsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "album-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Genre: Rock \r\n\r\nArtist: AC/DC \r\n\r\nPrice:";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"album-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("Album - For Those About To Rock We Salute You");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAddtocartHyperlink
        {
            get
            {
                if ((this.mUIAddtocartHyperlink == null))
                {
                    this.mUIAddtocartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtocartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtocartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtocartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtocartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to cart";
                    this.mUIAddtocartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/2";
                    this.mUIAddtocartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtocartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:26641/ShoppingCart/AddToCart/2";
                    this.mUIAddtocartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIAddtocartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/ShoppingCart/AddToCart/2\" length=";
                    this.mUIAddtocartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtocartHyperlink.WindowTitles.Add("Album - For Those About To Rock We Salute You");
                    #endregion
                }
                return this.mUIAddtocartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAddtocartHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMainPane : HtmlDiv
    {
        
        public UIMainPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "main";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "For Those About To Rock We Salute You\r\n\r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"main\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Album - For Those About To Rock We Salute You");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIForThoseAboutToRockWImage
        {
            get
            {
                if ((this.mUIForThoseAboutToRockWImage == null))
                {
                    this.mUIForThoseAboutToRockWImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIForThoseAboutToRockWImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIForThoseAboutToRockWImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIForThoseAboutToRockWImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "For Those About To Rock We Salute You";
                    this.mUIForThoseAboutToRockWImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Content/Images/placeholder.gif";
                    this.mUIForThoseAboutToRockWImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:26641/Content/Images/placeholder.gif";
                    this.mUIForThoseAboutToRockWImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIForThoseAboutToRockWImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"For Those About To Rock We Salute Y";
                    this.mUIForThoseAboutToRockWImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIForThoseAboutToRockWImage.WindowTitles.Add("Album - For Those About To Rock We Salute You");
                    #endregion
                }
                return this.mUIForThoseAboutToRockWImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIForThoseAboutToRockWImage;
        #endregion
    }
}
