// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITestAutomationPageObjects.PageObjects.ShoppingCart.ShoppingCartClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class ShoppingCart
    {
        
        #region Properties
        public UIShoppingCartWindowsIWindow UIShoppingCartWindowsIWindow
        {
            get
            {
                if ((this.mUIShoppingCartWindowsIWindow == null))
                {
                    this.mUIShoppingCartWindowsIWindow = new UIShoppingCartWindowsIWindow();
                }
                return this.mUIShoppingCartWindowsIWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIShoppingCartWindowsIWindow mUIShoppingCartWindowsIWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIShoppingCartWindowsIWindow : BrowserWindow
    {
        
        public UIShoppingCartWindowsIWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Shopping Cart";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Shopping Cart");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIShoppingCartDocument UIShoppingCartDocument
        {
            get
            {
                if ((this.mUIShoppingCartDocument == null))
                {
                    this.mUIShoppingCartDocument = new UIShoppingCartDocument(this);
                }
                return this.mUIShoppingCartDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIShoppingCartDocument mUIShoppingCartDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIShoppingCartDocument : HtmlDocument
    {
        
        public UIShoppingCartDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Shopping Cart";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ShoppingCart";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:26641/ShoppingCart";
            this.WindowTitles.Add("Shopping Cart");
            #endregion
        }
        
        #region Properties
        public UIMainPane UIMainPane
        {
            get
            {
                if ((this.mUIMainPane == null))
                {
                    this.mUIMainPane = new UIMainPane(this);
                }
                return this.mUIMainPane;
            }
        }
        #endregion
        
        #region Fields
        private UIMainPane mUIMainPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMainPane : HtmlDiv
    {
        
        public UIMainPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "main";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "$(function () { // Document.ready -> lin";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"main\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Shopping Cart");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICheckoutHyperlink
        {
            get
            {
                if ((this.mUICheckoutHyperlink == null))
                {
                    this.mUICheckoutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICheckoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICheckoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICheckoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICheckoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Checkout >>";
                    this.mUICheckoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Checkout/AddressAndPayment";
                    this.mUICheckoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICheckoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:26641/Checkout/AddressAndPayment";
                    this.mUICheckoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICheckoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Checkout/AddressAndPayment\"";
                    this.mUICheckoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUICheckoutHyperlink.WindowTitles.Add("Shopping Cart");
                    #endregion
                }
                return this.mUICheckoutHyperlink;
            }
        }
        
        public HtmlTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new HtmlTable(this);
                    #region Search Criteria
                    this.mUIItemTable.SearchProperties[HtmlTable.PropertyNames.Id] = null;
                    this.mUIItemTable.SearchProperties[HtmlTable.PropertyNames.Name] = null;
                    this.mUIItemTable.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Album Name \r\n\r\nPrice (each) \r\n\r\nQuantity";
                    this.mUIItemTable.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = null;
                    this.mUIItemTable.FilterProperties[HtmlTable.PropertyNames.RowCount] = "3";
                    this.mUIItemTable.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "4";
                    this.mUIItemTable.FilterProperties[HtmlTable.PropertyNames.Class] = null;
                    this.mUIItemTable.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
                    this.mUIItemTable.WindowTitles.Add("Shopping Cart");
                    #endregion
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICheckoutHyperlink;
        
        private HtmlTable mUIItemTable;
        #endregion
    }
}
