// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITestAutomationPageObjects.PageObjects.Account.AccountLogonClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class AccountLogon
    {
        
        #region Properties
        public UILogOnWindowsInternetWindow UILogOnWindowsInternetWindow
        {
            get
            {
                if ((this.mUILogOnWindowsInternetWindow == null))
                {
                    this.mUILogOnWindowsInternetWindow = new UILogOnWindowsInternetWindow();
                }
                return this.mUILogOnWindowsInternetWindow;
            }
        }
        #endregion
        
        #region Fields
        private UILogOnWindowsInternetWindow mUILogOnWindowsInternetWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UILogOnWindowsInternetWindow : BrowserWindow
    {
        
        public UILogOnWindowsInternetWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Log On";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Log On");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UILogOnDocument UILogOnDocument
        {
            get
            {
                if ((this.mUILogOnDocument == null))
                {
                    this.mUILogOnDocument = new UILogOnDocument(this);
                }
                return this.mUILogOnDocument;
            }
        }
        #endregion
        
        #region Fields
        private UILogOnDocument mUILogOnDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UILogOnDocument : HtmlDocument
    {
        
        public UILogOnDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log On";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/LogOn";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:26641/Account/LogOn?ReturnUrl=%2fStoreManager%2f";
            this.WindowTitles.Add("Log On");
            #endregion
        }
        
        #region Properties
        public UIMainPane UIMainPane
        {
            get
            {
                if ((this.mUIMainPane == null))
                {
                    this.mUIMainPane = new UIMainPane(this);
                }
                return this.mUIMainPane;
            }
        }
        
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "UserName";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "UserName";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User name";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"UserName\" id=\"UserName\" type=\"text";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUsernameEdit.WindowTitles.Add("Log On");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" id=\"Password\" type=\"pass";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Log On");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlCheckBox UIRemembermeCheckBox
        {
            get
            {
                if ((this.mUIRemembermeCheckBox == null))
                {
                    this.mUIRemembermeCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIRemembermeCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = "RememberMe";
                    this.mUIRemembermeCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "RememberMe";
                    this.mUIRemembermeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Value] = "true";
                    this.mUIRemembermeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.LabeledBy] = "Remember me?";
                    this.mUIRemembermeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIRemembermeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIRemembermeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=\"RememberMe\" id=\"RememberMe\" type=\"";
                    this.mUIRemembermeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "3";
                    this.mUIRemembermeCheckBox.WindowTitles.Add("Log On");
                    #endregion
                }
                return this.mUIRemembermeCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private UIMainPane mUIMainPane;
        
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlCheckBox mUIRemembermeCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMainPane : HtmlDiv
    {
        
        public UIMainPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "main";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Log On\r\n\r\nPlease enter your user name an";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"main\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Log On");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRegisterHyperlink
        {
            get
            {
                if ((this.mUIRegisterHyperlink == null))
                {
                    this.mUIRegisterHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:26641/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Account/Register\"";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIRegisterHyperlink.WindowTitles.Add("Log On");
                    #endregion
                }
                return this.mUIRegisterHyperlink;
            }
        }
        
        public HtmlInputButton UILogOnButton
        {
            get
            {
                if ((this.mUILogOnButton == null))
                {
                    this.mUILogOnButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILogOnButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILogOnButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILogOnButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log On";
                    this.mUILogOnButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILogOnButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILogOnButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUILogOnButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "type=\"submit\" value=\"Log On\"";
                    this.mUILogOnButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUILogOnButton.WindowTitles.Add("Log On");
                    #endregion
                }
                return this.mUILogOnButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRegisterHyperlink;
        
        private HtmlInputButton mUILogOnButton;
        #endregion
    }
}
